language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
# command to run tests
script:
  - py.test --cov=flaskbb --cov-report=term-missing tests
after_success:
  - coveralls
