curriculum= [{desc:”Annex A - Professionalism in Medical Practice”,competencies:[
{level:’all’,desc:”CC_D3_01”,desc:”Commits to the importance of being a good team member, working collaboratively, striving for high standards by all”},
{level:’all’,desc:”CC_D5_03”,desc:”Commits to the principle of inter-professional cooperation for audit/quality improvement projects in improving practice”},
{level:’all’,desc:”CC_D5_04”,desc:”Commits to contributing to quality improvement processes”},
{level:’all’,desc:”CC_D9_01”,desc:”Commits to behaving in accordance with the principles of medical ethics”},
{level:’all’,desc:”CC_D9_02”,desc:”Commits to following the guidance given by the GMC on confidentiality”},
{level:’all’,desc:”CC_D9_03”,desc:”Commits to the principle of the Caldicott Guardian and Information Governance”},
{level:’all’,desc:”CC_D12_03”,desc:”Commits to understanding, and incorporating into practice, issues surrounding data collection and analysis“},
{level:’all’,desc:”CC_D12_05”,desc:”Commits to understanding the ways in which data, information and knowledge come together in the development of guidelines, protocols and care pathways“},
]},
{desc:”Annex G - Teaching and Training, Academic and Research (including Audit), Quality Improvement, and Management”, competencies:[
{level:’core’,code:”AR_BK_05”,desc:”Understands the steps involved in completing the audit cycle”},
{level:’core’,code:”AR_BK_06”,desc:”Understands the different methods of obtaining data for audit including patient feedback questionnaires, hospital sources and national reference data”},
{level:’core’,code:”AR_BK_07”,desc:”Understands the role of audit including but not exclusively improving patient care and services, risk management etc”},
{level:’core’,code:”AR_BK_10”,desc:”Outlines the difference between audit and research”},
{level:’core’,code:”AR_BS_10”,desc:”Contributes data to local or national audit”},
{level:’core’,code:”AR_BS_11”,desc:”Describes the Plan, Do, Study, Act (PDSA) audit cycle and takes an audit through the first steps”},
{level:’core’,code:”AR_BS_12”,desc:”Demonstrate presentation skills to a live audience including the planning and preparation of the presentation”},
{level:’int’,code:”AR_IK_04”,desc:”Understands the links between audit and quality improvement”},
{level:’int’,code:”AR_IK_07”,desc:”Knows about local and national research guidelines”},
{level:’int’,code:”AR_IK_08”,desc:”Demonstrates a knowledge of research principles”},
{level:’int’,code:”AR_IS_03”,desc:”Supports audit by junior medical trainees and within the multidisciplinary team”},
{level:’int’,code:”AR_IS_04”,desc:”Suggests ideas for local audit”},
{level:’higher’,code:”AR_HK_01”,desc:”Understands their role in supporting quality through participating in and promoting audit”},
{level:’higher’,code:”AR_HK_02”,desc:”Understands the ethical issues relating to audit”},
{level:’higher’,code:”AR_HK_03”,desc:”Know the principles of research governance”},
{level:’higher’,code:”AR_HS_05”,desc:”Designs, implements and completes audit cycles”},
{level:’higher’,code:”AR_HS_07”,desc:”Identifies problems and develops standards for local audit”},
{level:’higher’,code:”AR_HS_08”,desc:”Proposes and tests ways to improve patient care”},
{level:’higher’,code:”AR_HS_09”,desc:”Compares the results of an audit with criteria and standards to reach conclusions”},
{level:’higher’,code:”AR_HS_11”,desc:”Undertakes a literature review in relation to a clinical problem or topic and presents the same”},
{level:’higher’,code:”AR_HS_12”,desc:”Encourages discussion amongst colleagues in evidence-based practice”},
{level:’higher’,code:”AR_HS_13”,desc:”Uses the findings of an audit to develop and implement change”},
{level:’higher’,code:”AR_HS_14”,desc:”Contributes to local and national audit projects as appropriate “},
{level:’adv’,code:”AR_AK_06”,desc:”Presents clinical and academic work at deanery and national scientific meetings where possible submitting reports for presentation or posters”},
{level:’adv’,code:”AR_AK_07”,desc:”Knows how to produce a poster summarising a project for presentation”},
{level:’adv’,code:”AR_AK_08”,desc:”Understands material specifically related to their ‘project’”},
{level:’adv’,code:”AR_AS_01”,desc:”Contributes to the development of local and national clinical guidelines and protocol”},
{level:’adv’,code:”AR_AS_02”,desc:”Champions practice change supported by audit”},
{level:’adv’,code:”AR_AS_04”,desc:”Leads a complete audit cycle including development of conclusions, the changes needed for improvement, implementation of findings and re-audit to assess effectiveness of changes”},
{level:’adv’,code:”AR_AS_05”,desc:”Shows willingness to encourage and take part in research”},
{level:’adv’,code:”AR_AS_06”,desc:”Applies for appropriate ethical research approval”},
{level:’adv’,code:”AR_AS_10”,desc:”Attends relevant national and international meetings”}
]}]
